gui:
  showFileTree: true
  showCommandLog: false
  nerdFontsVersion: "3"
  # Catppuccin Mocha
  theme:
    activeBorderColor:
      - "#fab387"
      - "bold"
    inactiveBorderColor:
      - "#6c7086"
    searchingActiveBorderColor:
      - "#f9e2af"
      - "bold"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#cba6f7"
    markedBaseCommitFgColor:
      - "#89b4fa"
    markedBaseCommitBgColor:
      - "#f9e2af"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"

os:
  edit: '[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send ''<C-\><C-n><Cmd>lua vim.api.nvim_win_close(0, true);vim.cmd("edit "..vim.fn.fnameescape({{filename}}))<CR>'' || nvim {{filename}}'
  editAtLine: '[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send ''<C-\><C-n><Cmd>lua vim.api.nvim_win_close(0, true);vim.cmd("edit +{{line}} "..vim.fn.fnameescape({{filename}}))<CR>'' || nvim +{{line}} {{filename}}'

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true

git:
  pagers:
    - pager: |
        delta --syntax-theme "$(
          defaults read -g AppleInterfaceStyle 2>/dev/null \
            | grep -qi dark && echo 'OneHalfDark' || echo 'OneHalfLight'
        )" --paging=never --line-numbers \
          --line-numbers-left-format="" \
          --line-numbers-right-format="{np:^4}│ " \
          --hyperlinks \
          --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  autoFetch: false
  autoRefresh: false
