gui:
  # Catppuccin Latte
  theme:
    activeBorderColor:
      - "#fe640b"
      - "bold"
    inactiveBorderColor:
      - "#6c6f85"
    searchingActiveBorderColor:
      - "#df8e1d"
      - "bold"
    optionsTextColor:
      - "#1e66f5"
    selectedLineBgColor:
      - "#ccd0da"
    cherryPickedCommitFgColor:
      - "#1e66f5"
    cherryPickedCommitBgColor:
      - "#8839ef"
    markedBaseCommitFgColor:
      - "#1e66f5"
    markedBaseCommitBgColor:
      - "#df8e1d"
    unstagedChangesColor:
      - "#d20f39"
    defaultFgColor:
      - "#4c4f69"
