gui:
  showFileTree: true
  showCommandLog: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

os:
  edit: '[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send ''<C-\><C-n><Cmd>lua vim.api.nvim_win_close(0, true);vim.cmd("edit "..vim.fn.fnameescape({{filename}}))<CR>'' || nvim {{filename}}'
  editAtLine: '[ -n "$NVIM" ] && nvim --server "$NVIM" --remote-send ''<C-\><C-n><Cmd>lua vim.api.nvim_win_close(0, true);vim.cmd("edit +{{line}} "..vim.fn.fnameescape({{filename}}))<CR>'' || nvim +{{line}} {{filename}}'

promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true

git:
  pagers:
    - pager: |
        delta --syntax-theme "$(
          defaults read -g AppleInterfaceStyle 2>/dev/null \
            | grep -qi dark && echo 'OneHalfDark' || echo 'OneHalfLight'
        )" --paging=never --line-numbers \
          --line-numbers-left-format="" \
          --line-numbers-right-format="{np:^4}│ " \
          --hyperlinks \
          --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  autoFetch: false
  autoRefresh: false
