projects = [
  { path = "~/work/*", display_depth = 2 },
  { path = "~/personal/*", display_depth = 2 },
  { path = "~/projects/*", display_depth = 2 },
  { path = "~/.local/share/chezmoi" },
]

[dashboard]
zoom_on_switch = false
